---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache; limitations in HA deployment in MAZ, SAZ, multiple availability xone, single availability zone Azure CVO, PSSDv2, premium SSD v2 limitation in CVO, flash cache limitation in CVO 
summary: 這些已知限制僅適用於Cloud Volumes ONTAP Microsoft Azure中的某些功能。 
---
= Azure 中 Cloud Volumes ONTAP 的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
下列已知限制僅適用於Cloud Volumes ONTAP Microsoft Azure中的功能。請務必同時檢閱 link:reference-limitations.html["所有雲端供應商的不完整功能Cloud Volumes ONTAP"]。



== 使用 Azure VM 延伸功能的限制

Cloud Volumes ONTAP不支援 Azure 虛擬機器 (VM) 擴展，因為它們會影響BlueXP管理作業。在部署期間， BlueXP會阻止在您的虛擬機器上安裝任何擴充功能。如果您現有的Cloud Volumes ONTAP VM 上已安裝擴展，請聯絡 Microsoft Azure 支援將其刪除。如需指導，請參閱知識庫 (KB) 文章 https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["Azure VM 管理擴充功能可以安裝到 Cloud Volume ONTAP中嗎？"^]

從 2025 年 7 月 14 日開始，如果在您的Cloud Volumes ONTAP VM 上偵測到 VM 擴展， NetApp將發送電子郵件並在BlueXP中通知您。



== HA 配置的進階 SSD v2 磁碟限制

進階 SSD v2 託管磁碟對於 Azure 中的高可用性 (HA) 部署有以下限制：

* 非區域性區域的 HA 部署不支援。
* 不支援跨多個可用區域的 HA 部署。
* 僅在單一可用區域內部署的 HA 配置中支援。


若要將 Premium SSD v2 託管磁碟與Cloud Volumes ONTAP HA 設定一起使用，請確保符合下列要求：

* Cloud Volumes ONTAP版本為 9.15.1 或更高版本。
* HA 部署位於 Azure 單一可用區域。
* 所選區域和區域支援高級 SSD v2 託管磁碟。有關受支援區域的信息，請參閱 https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Microsoft Azure 網站：按地區提供的產品"^]。


有關更多信息，請參閱 https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#support-for-premium-ssd-v2-managed-disks-in-azure["Azure 中對進階 SSD v2 託管磁碟的支持"^] 。



== 在單一可用性區域中部署 HA 的限制

從Cloud Volumes ONTAP 9.15.1 開始，您可以在 Azure 中的單一可用區域 (AZ) 中以 HA 模式部署虛擬機器 (VM) 執行個體。有關支援此功能的標準的信息，請參閱 https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-in-azure["在 Azure 的單一可用性區域中部署 HA 配對"^]。

如果 Cloud Volumes ONTAP 版本早於 9.15.1 ，或不符合上述任何條件，則使用可用度集的先前部署模式即會生效。這僅適用於 HA 組態。



== Flash Cache限制

Cloud Volumes ONTAP 在某些 VM 類型中使用本機 NVMe 儲存設備做為 _Flash Caches_ 。請注意此限制：

* 不支援重新開機後的快取重新暖機。




== HA 部署的限制

某些區域不支援 HA 對。

https://bluexp.netapp.com/cloud-volumes-global-regions["檢視支援的Azure地區清單"^]。
