---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.15.1 包含新的增強功能。 
---
= Cloud Volumes ONTAP 9.15.1 的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.15.1 包含新的增強功能。

最新版的BlueXP也會提供其他功能和增強功能。請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^] 以取得詳細資料。



== 9.15.1 GA （ 2024 年 8 月 22 日）

Cloud Volumes ONTAP 9.15.1 GA 現已在 AWS 、 Azure 和 Google Cloud 中推出。GA 版本可用於部署和升級。此版本包含下列新功能與增強功能。



=== 支援 Azure 上的 Premium SSD v2 託管磁碟

Azure 上的 Cloud Volumes ONTAP 系統現在支援 Premium SSD v2 託管磁碟。相較於 Premium SSD 託管磁碟、這些優質磁碟可為單一節點和高可用度（ HA ）配對提供更高的效能、並以更低的成本提供更低的延遲。與其他託管磁碟一樣、最大磁碟大小為 32 TiB 。可設定優質 SSD v2 託管磁碟的效能（容量、處理量和 IOPS ）、讓工作負載符合成本效益、同時滿足不斷變動的效能需求。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-storage.html#azure-storage["瞭解 Azure 儲存設備"]。



=== 在 Azure 上的單一可用性區域中部署 HA 配對

從 Cloud Volumes ONTAP 9.15.1 開始、您可以在 Azure 上的單一可用性區域（ AZs ）中、以 HA 模式部署虛擬機器（ VM ）執行個體。與先前的非分區部署不同、 Cloud Volumes ONTAP 9.15.1 使用 Microsoft 虛擬機器擴充集、以靈活協調模式部署所有資源、包括在同一個 AZ 內獨立的故障網域、以確保最佳可用度。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-azure.html["瞭解 Azure 中的高可用度配對"]。



=== 支援虛擬機器擴充集、以統一化所有 Azure HA 類型

Cloud Volumes ONTAP 9.15.1 利用 Azure 上彈性協調模式中的虛擬機器擴充集、在單一可用性區域中部署虛擬機器（ VM ）執行個體、以實現高可用度（ HA ）配對。

此部署模式依預設會使用 Premium SSD v2 託管磁碟。當符合下列條件時、它涵蓋 HA 模式、 Pageblob 、本機備援儲存（ LRS ）、區域備援儲存（ ZRS ）或多區域、以及 LRS 區域（單一 AZ ）的所有風格：

* Cloud Volumes ONTAP 版本為 9.15.1 或更新版本。
* 該區域支援以彈性協調模式進行虛擬機器擴充集。如需支援區域的相關資訊、請 https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Microsoft Azure 網站：依地區提供的產品"^]參閱。
* 區域中所選的區域支援靈活協調模式中的虛擬機器擴充集。
* 訂閱已註冊 Microsoft `Microsoft.Compute/VMOrchestratorZonalMultiFD` 功能。
+
若要深入瞭解、請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-otc-azure.html#launching-a-cloud-volumes-ontap-ha-pair-in-azure["在Cloud Volumes ONTAP Azure中啟動一套功能完善的"^]和 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-saz-feature.html["為單一可用性區域啟用 VMOrchestratorZonalMultiFD"^]。



若未符合上述任一條件、先前的 LRS 非分區部署即會生效。



== 升級注意事項：

請閱讀這些附註、深入瞭解升級至此版本的相關資訊。



=== 如何升級

必須從BlueXP完成升級。Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在BlueXP通知您時進行升級"^]。



=== 支援的升級途徑

您可以從 9.15.0 和 9.14.1 版本升級至 Cloud Volumes ONTAP 9.15.1 。BlueXP會提示您將合格Cloud Volumes ONTAP 的更新版升級至此版本。



=== 停機

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。




=== 不再支援c4、m4和r4執行個體

在AWS中Cloud Volumes ONTAP 、不再支援C4、M4和R4 EC2執行個體類型。如果現有的系統執行於c4、m4或r4執行個體類型、則必須變更為c5、m5或R5執行個體系列中的執行個體類型。您必須變更執行個體類型、才能升級至此版本。

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["瞭解如何變更EC2執行個體類型Cloud Volumes ONTAP 以供使用"^]。

請參閱 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp支援"^] 以深入瞭解這些執行個體類型的終止可用度和支援。
