---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Google Cloud支援多Cloud Volumes ONTAP 種支援的支援功能。 
---
= 支援 Google Cloud 中的 Cloud Volumes ONTAP 組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud支援多Cloud Volumes ONTAP 種支援的支援功能。



== 依授權支援的組態

Cloud Volumes ONTAP 在 Google Cloud 中既可以作為單節點系統使用，也可以作為高可用性（HA）節點對使用，以實現容錯和不間斷操作。

不支援將單節點系統升級為 HA 配對。如果您想在單節點系統和 HA 配對之間切換，則需要部署新系統並將資料從現有系統複寫到新系統。

可在雲端供應商的保留或隨需VM執行個體上執行。Cloud Volumes ONTAP不支援使用其他VM執行個體類型的解決方案。

[role="tabbed-block"]
====
.容量型授權
--
[cols="h,d,d,d"]
|===
|  | Freemium | 已優化^4^ | 容量型授權（ Essentials 與 Professional ） 


| 最大系統容量（磁碟+物件儲存） | 500 GiB  a| 
透過基於容量的許可，每個Cloud Volumes ONTAP系統都支援分層到物件儲存。總分層容量可以擴展到雲端提供者的儲存桶限制。雖然許可證沒有施加容量限制，但您應該遵循 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool最佳實踐"^]確保在配置和管理分層時實現最佳效能、可靠性和成本效率。



| 支援的機器類型：^1^  a| 
* N1-Standard-8 ^1^
* N1-Standard-32 ^1^
* n2-Standard-4
* n2-Standard-8.
* n2-Standard-16
* n2-Standard-32
* n2-Standard-48
* n2-Standard-64

 a| 
* n2-Standard-4
* n2-Standard-8.

 a| 
* N1-Standard-8 ^1^
* N1-Standard-32 ^1^
* n2-Standard-4
* n2-Standard-8.
* n2-Standard-16
* n2-Standard-32
* n2-Standard-48
* n2-Standard-64




| 支援的磁碟類型^2^ 3+| 平衡式持續磁碟 ^3^ 、效能（ SSD ）持續磁碟 ^3^ 和標準（ HDD ）持續磁碟。 
|===
附註：

. ^1^ 在 Google Cloud 中部署Cloud Volumes ONTAP的新實例時， NetApp控制台上不再可選擇 n1 系列機器。n1 系列機器將保留，並且僅在較舊的現有系統中支援。從 9.8 版本開始，Google Cloud 才支援Cloud Volumes ONTAP的新部署。我們建議您切換到與Cloud Volumes ONTAP 9.8 及更高版本相容的 n2 系列機器。不過，n1 系列機器將可用於透過 API 進行的新部署。
+
全新Cloud Volumes ONTAP 的功能不再支援custom 4-16384機器類型。如果您在此機器類型上執行現有的系統、您可以繼續使用、但我們建議您切換至n2-Standard-4機器類型。

. ^2^ 磁碟限制可防止您單獨使用磁碟來達到最大系統容量限制。您可以透過達到容量限制 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["將非作用中資料分層至物件儲存設備"^]。
+
link:reference-limits-gcp.html["深入瞭解Google Cloud的磁碟限制"]。

. ^3^ 使用平衡式持續磁碟和效能（ SSD ）持續磁碟時，會啟用增強的寫入效能。
+
從 Cloud Volumes ONTAP 9.13.0 開始、 _Flash Caches_ 、高寫入速度、以及高達 8 、 896 位元組的最大傳輸單元（ MTU ）、可用於下列 HA 配對部署執行個體：

+
** n2-Standard-16
** n2-Standard-32
** n2-Standard-48
** n2-Standard-64
+
您可以在部署符合資格的執行個體類型時啟用_Flash Cache和高速寫入速度。若要啟用最大傳輸單位8、896位元組、您必須選擇VPC-1、VPC-2或VPC-3進行部署。MTU越高、網路處理量就越高。如需啟動其中一個部署的詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["在Google Cloud上啟動HA配對"]。

+

NOTE: _Flash快取_、高寫入模式和8、896的MTU是功能相依的、無法在設定的執行個體中個別停用。



. ^4^ 自 2025 年 8 月 11 日起， Cloud Volumes ONTAP Optimized 授權將被棄用，並且將不再可在 Google Cloud 市場中以即用即付 (PAYGO) 訂閱的方式購買或續訂。有關信息，請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["更新功能 Cloud Volumes ONTAP"^]。


--
.節點型授權
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO瀏覽 | PAYGO標準 | PAYGO Premium | 節點型BYOL 


| 最大系統容量（磁碟+物件儲存） | 2 TB ^2^ | 10 TiB | 368TiB | 每個授權368TiB 


| 支援的機器類型^3^  a| 
* n2-Standard-4

 a| 
* N1 標準 -8 ^3^
* n2-Standard-8.

 a| 
* N1 標準 -32 ^3^
* n2-Standard-16
* n2-Standard-32
* n2-Standard-48
* n2-Standard-64

 a| 
* N1 標準 -8 ^3^
* N1 標準 -32 ^3^
* n2-Standard-4
* n2-Standard-8.
* n2-Standard-16
* n2-Standard-32
* n2-Standard-48
* n2-Standard-64




| 支援的磁碟類型 4+| 平衡式持續磁碟 ^4^ 、效能（ SSD ）持續磁碟 ^4^ 和標準（ HDD ）持續磁碟。 
|===
附註：

. ^1^ 磁碟限制可防止您單獨使用磁碟來達到最大系統容量限制。您可以透過達到容量限制 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["將非作用中資料分層至物件儲存設備"^]。
+
link:reference-limits-gcp.html["深入瞭解Google Cloud的磁碟限制"]。

. ^2^ PAYGO Explore 不支援將資料分層至 Google Cloud Storage 。
. ^3^ 在 Google Cloud 中部署Cloud Volumes ONTAP的新實例時，控制台上不再可選擇 n1 系列機器。n1 系列機器將保留，並且僅在較舊的現有系統中支援。從 9.8 版本開始，Google Cloud 才支援Cloud Volumes ONTAP的新部署。我們建議您切換到與Cloud Volumes ONTAP 9.8 及更高版本相容的 n2 系列機器。然而，n1 系列機器將可用於透過 API 執行的新部署。
+
全新Cloud Volumes ONTAP 的功能不再支援custom 4-16384機器類型。如果您在此機器類型上執行現有的系統、您可以繼續使用、但我們建議您切換至n2-Standard-4機器類型。

. ^4^ 使用平衡式持續磁碟和效能（ SSD ）持續磁碟時，會啟用增強的寫入效能。


控制台顯示了標準和 BYOL 支援的額外機器類型：n1-highmem-4。然而，這種機器類型並不適合生產環境。我們僅將其用於特定的實驗室環境。

下列HA配對部署執行個體可從發行版本9.13.0、Cloud Volumes ONTAP _Flash Cache、高速寫入速度及最大傳輸單元（MTU）8、896位元組開始使用：

* n2-Standard-16
* n2-Standard-32
* n2-Standard-48
* n2-Standard-64


您可以在部署符合資格的執行個體類型時啟用_Flash Cache和高速寫入速度。若要啟用最大傳輸單位8、896位元組、您必須選擇VPC-1、VPC-2或VPC-3進行部署。MTU越高、網路處理量就越高。如需啟動其中一個部署的詳細資訊、請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["在Google Cloud上啟動HA配對"]。


NOTE: _Flash快取_、高寫入模式和8、896的MTU是功能相依的、無法在設定的執行個體中個別停用。

--
====
有關特定機器類型的更多信息，請參閱 Google Cloud 文件：

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["n1系列通用機型"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["N2系列通用機型"^]




== 支援的磁碟大小

在Google Cloud中、Aggregate最多可包含6個相同類型和大小的磁碟。支援下列磁碟大小：

* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB




== 支援的地區

如需 Google Cloud 地區支援 https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes全球區域"^]、請參閱。
