---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.18.1 包含一項新的增強功能。 
---
= Cloud Volumes ONTAP 9.18.1 的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
現在您可以部署和升級到 Cloud Volumes ONTAP 9.18.1。您可以在 NetApp Console 中查看此版本的基本版本以及可用於部署和升級的最新修補程式版本。

若要了解 Cloud Volumes ONTAP 最新版本 NetApp Console 中引入的 Cloud Volumes ONTAP 功能，請參閱新增功能 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^]。



== 9.18.1 GA（2026 年 2 月 10 日）

Cloud Volumes ONTAP 9.18.1 正式版現已在 Amazon Web Services（AWS）和 Microsoft Azure 上發布，可供部署和升級。此版本暫不支援在 Google Cloud 上部署和升級。



== 升級附註

請閱讀這些附註、深入瞭解升級至此版本的相關資訊。



=== 如何升級

Cloud Volumes ONTAP的升級必須透過控制台完成。您不應使用系統管理員或 CLI 升級Cloud Volumes ONTAP 。這樣做會影響系統穩定性。

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["了解控制台通知您時如何升級"^] 。



=== 支援的升級途徑

您可以從 AWS 和 Azure 上的 9.17.1 P1 及更高版本修補程式升級至 Cloud Volumes ONTAP 9.18.1。NetApp Console 將提示您將符合條件的 Cloud Volumes ONTAP 系統升級至此版本。


NOTE: Cloud Volumes ONTAP 9.18.1 無法在 Google Cloud 中進行升級。



=== 停機

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不會中斷營運， I/O 也不會中斷。在此不中斷升級程序期間，每個節點都會一起升級，以繼續為用戶端提供 I/O 服務。

