---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: 包含新的增強功能。Cloud Volumes ONTAP 
---
= 更新內容Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
更新功能包括更新功能。Cloud Volumes ONTAP

最新版的BlueXP（前身為Cloud Manager）也引進其他功能與增強功能。請參閱 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^] 以取得詳細資料。



== 不再支援的c4、m4和r4執行個體（2022年10月28日）

在AWS中Cloud Volumes ONTAP 、不再支援C4、M4和R4 EC2執行個體類型。如果現有系統執行的是c4、m4或r4執行個體類型、則必須變更為c5、m5或R5執行個體系列中的執行個體類型。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["瞭解如何變更EC2執行個體類型Cloud Volumes ONTAP 以供使用"^]。

請參閱 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp支援"^] 以深入瞭解這些執行個體類型的終止可用度和支援。



== 9.11.1 P3（2022年10月19日）

如果Cloud Volumes ONTAP 您有執行3.9.22版或更新版本的Connector、現在所有雲端供應商都可以使用9.11.1 P3修補程式。BlueXP會提示您將現有系統升級至此修補程式版本。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.11.1P3["檢視P3修補程式中修正的錯誤清單"^] （需登入 NetApp 支援網站）。



== 9.11.1 GA（2022年8月1日）

目前已推出《The General Availability》（GA）版Cloud Volumes ONTAP 的《The》（英文）。GA版本包含錯誤修正。



== 9.11.1 RC1（2022年6月7日）

AWS、Azure和Google Cloud現已提供適用的發行候選版本1。Cloud Volumes ONTAP此版本包含下列新功能與增強功能。



=== 效能提升

我們已提升9.11.1或更新版本中新集合體的讀取效能。



=== 提高儲存效率

從9.11.1版開始、所有啟用儲存效率的新磁碟區都將包含一項稱為溫度敏感儲存效率的新壓縮功能。不再使用前一代壓縮功能。

溫度敏感的儲存效率會根據資料溫度或資料使用頻率來壓縮資料。冷資料或不常使用的資料會以較高的壓縮比率重新壓縮、以提高儲存效率。



=== AWS中的VPC共享

AWS現在支援搭配VPC共享的支援使用支援的功能組。Cloud Volumes ONTAPVPC共用功能可讓您的組織與其他AWS帳戶共用子網路。網路（VPC、子網路和路由表）位於VPC擁有者帳戶中、而HA組態的EC2執行個體則位於使用共用子網路的參與者帳戶中。

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploy-aws-shared-vpc.html["瞭解如何在共用子網路中部署HA配對"^]



=== 全新AWS區域支援

AWS雅加達地區（ap東南3區）現在支援此功能。Cloud Volumes ONTAP

https://cloud.netapp.com/cloud-volumes-global-regions["檢視Cloud Volumes ONTAP 支援區域的完整清單以供參閱"^]



=== 全新Azure區域支援

Azure Brazil東南亞地區現已支援此功能。Cloud Volumes ONTAP

https://cloud.netapp.com/cloud-volumes-global-regions["檢視Cloud Volumes ONTAP 支援區域的完整清單以供參閱"^]



=== Google Cloud支援24個儲存VM

大多數組態現在支援24個儲存VM Cloud Volumes ONTAP 、可在Google Cloud中使用支援。

* link:reference-limits-gcp.html#storage-vm-limits["深入瞭解Google Cloud中的儲存VM限制"]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-gcp.html["瞭解如何在Cloud Volumes ONTAP Google Cloud中建立資料服務儲存VM以供其使用"^]




=== 新的Google Cloud區域支援

目前在Milan（歐洲-西8）地區支援的是支援的2個HA配對。Cloud Volumes ONTAP

https://cloud.netapp.com/cloud-volumes-global-regions["檢視Cloud Volumes ONTAP 支援區域的完整清單以供參閱"^]



=== 修改新儲存VM的LIF服務

從本版本開始、如果您在Cloud Volumes ONTAP AWS或Azure的某個更新HA配對上建立新的儲存VM、則需要修改儲存VM的網路服務原則。需要修改服務、因為Cloud Volumes ONTAP 這樣可確保支援功能可將iSCSI LIF用於傳出管理連線。

請注意Cloud Volumes ONTAP 、由於BlueXP API會在建立期間為您設定LIF服務、因此不需要在Google Cloud中修改LIF服務。

您需要執行的命令會在下列頁面中指定：

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-aws.html["瞭解如何在AWS中建立額外的儲存VM"^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-azure.html["瞭解如何在Azure中建立額外的儲存VM"^]




== 全新不受支援ONTAP 的功能

不支援更新於《支援使用者驗證ONTAP 功能的更新功能：Cloud Volumes ONTAP在Cloud Volumes ONTAP 支援的情況下、在支援的系統上啟用多管理員驗證、將會產生不受支援的組態。



== 升級附註

請閱讀這些附註、深入瞭解升級至此版本的相關資訊。



=== 如何升級

必須從BlueXP完成升級。Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在BlueXP通知您時進行升級"^]。



=== 支援的升級途徑

您可以從Cloud Volumes ONTAP 9.11.0版和9.10.1版升級至版本的版本。BlueXP會提示您將合格Cloud Volumes ONTAP 的更新版升級至此版本。



=== 所需版本的Connector

BlueXP Connector必須執行3.9.19版或更新版本、才能部署新Cloud Volumes ONTAP 的版本的更新版本、並將現有系統升級至9.11.1版。


TIP: 連接器的自動升級預設為啟用、因此您應該執行最新版本。



=== 停機

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。

