---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.15.0 包含新的增強功能。 
---
= Cloud Volumes ONTAP 9.15.0 的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.15.0 包含新的增強功能。

最新版的BlueXP也會提供其他功能和增強功能。請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^] 以取得詳細資料。



== 9.15.0 P1 （ 2024 年 6 月 10 日）

Cloud Volumes ONTAP 9.15.0 P1 現已在 AWS 、 Azure 和 Google Cloud 中推出。P1 版本可用於部署和升級。

此版本包含新功能和增強功能。



=== Azure 中的影像驗證

增強的安全功能現在可用於驗證透過 Azure 匯出的 Cloud Volumes ONTAP 映像檔案的簽名。

如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-azure-image-verification.html["深入瞭解 Azure 影像驗證"^]。



=== Azure 頁面 Blobs 不再支援新的高可用度配對部署

從 Cloud Volumes ONTAP 9.15.0 P1 開始、新的高可用度配對部署不再支援 Azure 頁面 Blobs 。如果您目前在現有的高可用度配對部署中使用 Azure 頁面 Blobs 、您可以在 Edsv4 系列 VM 和 Edsv5 系列 VM 中移轉至較新的 VM 執行個體類型。

link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#ha-pairs["深入瞭解 Azure 支援的組態"^]。



== 升級附註

請閱讀這些附註、深入瞭解升級至此版本的相關資訊。



=== 如何升級

必須從BlueXP完成升級。Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在BlueXP通知您時進行升級"^]。



=== 支援的升級途徑

您可以從 9.14.1 版本升級至 Cloud Volumes ONTAP 9.15.0 。BlueXP會提示您將合格Cloud Volumes ONTAP 的更新版升級至此版本。



=== 停機

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。




=== 不再支援c4、m4和r4執行個體

在AWS中Cloud Volumes ONTAP 、不再支援C4、M4和R4 EC2執行個體類型。如果現有的系統執行於c4、m4或r4執行個體類型、則必須變更為c5、m5或R5執行個體系列中的執行個體類型。您必須變更執行個體類型、才能升級至此版本。

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["瞭解如何變更EC2執行個體類型Cloud Volumes ONTAP 以供使用"^]。

請參閱 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp支援"^] 以深入瞭解這些執行個體類型的終止可用度和支援。
