---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: 已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。 
---
= 所有雲端供應商的 Cloud Volumes ONTAP 已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。

下列限制適用於Cloud Volumes ONTAP 所有雲端供應商的解決方案：AWS、Azure和Google Cloud。



== 不支援ONTAP 的支援功能

下列功能Cloud Volumes ONTAP 不支援使用下列功能：

* Aggregate層級即時重複資料刪除技術
* Aggregate層級背景重複資料刪除技術
* 磁碟維護中心
* 磁碟資料抹除
* 鏡射FabricPool
* 光纖通道（FC）
* Flash資源池
* 無限Volume
* 介面群組
* 內部網路模式LIF容錯移轉
* MetroCluster
* 多管理員驗證
+
在Cloud Volumes ONTAP 支援的情況下、在支援的系統上啟用多管理員驗證、將會產生不受支援的組態。

* RAID4、RAID-DP、RAID-TEC 功能（支援RAID0）
* 服務處理器
* 支援一致性與企業模式（僅支援Cloud WORM）SnapLock
* SnapMirror同步
* VLAN
* SMB 持續可用性 (CA)
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["持續可用的 SMB 共享"^]不支援無中斷運作。





== 最大並行複寫作業數

無論執行個體類型或機器類型為何、每個節點的並行SnapMirror或SnapVault 支援Cloud Volumes ONTAP 物件傳輸數量上限為100。



== 雲端供應商快照不得用於您的備份與還原計畫

您不應將雲端供應商的快照作為Cloud Volumes ONTAP 還原資料的備份與恢復計畫的一部分。您應該一律使用ONTAP 「不間斷快照複本」或第三方備份解決方案來備份及還原Cloud Volumes ONTAP 以「支援」為主的資料。

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["了解如何使用NetApp Backup and Recovery 備份和還原ONTAP數據"^] 。


NOTE: 由資料一致性決定資料一致性。ONTAP WAFL只ONTAP 有當WAFL 機時、才能靜止不動的檔案系統來進行一致的備份。



== Cloud Volumes ONTAP 僅支援保留和隨需 VM 執行個體

可在雲端供應商的保留或隨需VM執行個體上執行。Cloud Volumes ONTAP不支援其他類型的VM執行個體。



== 不應使用自動應用程式資源管理解決方案

自動應用程式資源管理解決方案不應管理Cloud Volumes ONTAP 功能完善的系統。否則可能會變更不受支援的組態。例如、解決方案Cloud Volumes ONTAP 可能會變更為不受支援的VM執行個體類型。



== 軟體更新必須透過NetApp控制台完成

必須從NetApp控制台完成Cloud Volumes ONTAP的升級。您不應使用系統管理員或 CLI 升級Cloud Volumes ONTAP 。這樣做會影響系統穩定性。



== 不得從雲端供應商的主控台修改部署Cloud Volumes ONTAP

從雲端提供者的控制台變更Cloud Volumes ONTAP配置會導致設定不受支援。對控制台建立和管理的Cloud Volumes ONTAP資源的任何變更都可能影響系統穩定性和控制台管理系統的能力。


NOTE: 初始部署後、支援修改用於 Cloud Volumes ONTAP 資源的 Azure Subscription 名稱。



== 必須從控制台管理磁碟和聚合

必須直接從控制台建立和刪除所有磁碟和聚合。您不應從其他管理工具執行這些操作。這樣做會影響系統穩定性，妨礙將來添加磁碟的能力，並可能產生冗餘的雲端供應商費用。



== 不受授權限制SnapManager

支援以伺服器為單位的各個伺服器授權。SnapManager Cloud Volumes ONTAP不SnapManager 支援每個儲存系統（不支援此套件）授權。



== 第三方代理程式和延伸功能的限制

Cloud Volumes ONTAP 虛擬機器執行個體不支援協力廠商代理程式和 VM 延伸。
