---
sidebar: sidebar 
permalink: reference-limitations-aws.html 
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s, aws outpost, outposts 
summary: 這些已知的限制僅適用於Cloud Volumes ONTAP Amazon Web Services中的某些功能。 
---
= AWS的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
下列已知限制僅適用於Cloud Volumes ONTAP Amazon Web Services的功能。請務必同時檢閱 link:reference-limitations.html["所有雲端供應商的不完整功能Cloud Volumes ONTAP"]。



== AWS Outpost限制

如果您有 AWS Outpost 、您可以 Cloud Volumes ONTAP 在「工作環境」精靈中選取 Outpost VPC 、在該 Outpost 中部署功能不全。體驗與 AWS 中的任何其他 VPC 相同。請注意、您必須先在 AWS Outpost 部署 Connector 。

有幾項限制可以指出：

* 目前僅 Cloud Volumes ONTAP 支援單一節點的不支援系統
* 您可以搭配 Cloud Volumes ONTAP 使用的 EC2 執行個體僅限於您的據點所提供的項目
* 目前僅支援通用SSD（gp2）




== Flash Cache限制

C5D和R5D執行個體類型包括本機NVMe儲存設備、Cloud Volumes ONTAP 可做為_Flash Cache。請注意下列限制：

* 所有磁碟區都必須停用壓縮、才能充分發揮 Flash Cache 效能的改善效益。
+
從BlueXP建立磁碟區時、您可以選擇「無儲存效率」、也可以先建立磁碟區、然後再建立 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["使用 CLI 停用資料壓縮"^]。

* 重新開機後的快取重新溫熱功能不支援 Cloud Volumes ONTAP 使用此功能。




== Amazon CloudWatch回報的誤報

當閒置時、不釋放CPU Cloud Volumes ONTAP https://aws.amazon.com/cloudwatch/["Amazon CloudWatch"^] 可針對EC2執行個體回報高CPU警告、因為它能看到100%的使用率。您可以忽略此警報。使用「flex統計 資料」命令可顯示CPU的實際使用量。ONTAP



== 不支援立即儲存恢復的部分Cloud Volumes ONTAP

節點重新開機後、合作夥伴必須先同步資料、才能退回儲存設備。重新同步資料所需的時間取決於節點當機時用戶端寫入的資料量、以及恢復期間的資料寫入速度。

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha.html["瞭解儲存設備如何在Cloud Volumes ONTAP AWS上執行的一套功能不只是一套"^]。
