---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: 在Google Cloud中、由於儲存組態限制、可提供可靠的作業。Cloud Volumes ONTAP為獲得最佳效能、請勿將系統設定為最大值。 
---
= Google Cloud 中 Cloud Volumes ONTAP 的儲存限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
提供可靠作業的儲存組態限制。Cloud Volumes ONTAP為獲得最佳效能、請勿將系統設定為最大值。



== 依授權提供的最大系統容量

整個系統的最大容量Cloud Volumes ONTAP 取決於其授權。最大系統容量包括磁碟型儲存設備、以及用於資料分層的物件式儲存設備。

NetApp不支援超過系統容量限制。如果您達到授權容量上限、則BlueXP會顯示必要行動訊息、不再允許您新增其他磁碟。

在某些組態中、磁碟限制會讓您無法單獨使用磁碟來達到容量限制。您可以達到容量上限 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["將非作用中資料分層至物件儲存設備"^]。如需詳細資料、請參閱下列磁碟限制。

.基於容量的許可證的容量限制
透過基於容量的許可，每個Cloud Volumes ONTAP系統都支援分層到物件儲存。總分層容量可以擴展到雲端提供者的儲存桶限制。雖然許可證沒有施加容量限制，但您應該遵循 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool最佳實踐"^]確保在配置和管理分層時實現最佳效能、可靠性和成本效率。請參閱 https://cloud.google.com/storage/docs/buckets["Google Cloud 文件"^]了解更多。

其他許可證類型的容量限制::


[cols="25,75"]
|===
| 授權 | 最大系統容量（磁碟+物件儲存） 


| Freemium | 500 GB 


| PAYGO瀏覽 | 2 TB（Explore不支援資料分層） 


| PAYGO標準 | 10 TB 


| PAYGO Premium | 3668 TB 


| 節點型授權 | 2 PIB （需要多個授權） 
|===
.對於HA配對、每個節點或整個HA配對的授權容量限制是多少？
容量限制適用於整個HA配對。不是每個節點。例如、如果您使用Premium授權、則兩個節點之間最多可有368TB的容量。

.對於HA配對、鏡射資料是否會根據授權容量限制計算？
不，不是這樣的。 HA 對中的資料在節點之間同步鏡像，以便在 Google Cloud 發生故障時資料可用。例如，如果您在節點 A 上購買了 8 TB 磁碟， BlueXP也會在節點 B 上指派 8 TB 磁碟用於鏡像資料。雖然設定了 16 TB 的容量，但只有 8 TB 計入許可證限制。



== Aggregate限制

可將Google Cloud Platform磁碟分組為_aggregate。Cloud Volumes ONTAPAggregate可為磁碟區提供儲存設備。

[cols="2*"]
|===
| 參數 | 限制 


| 最大資料集合數^1^  a| 
* 99個用於單一節點
* 64個（用於整個HA配對）




| 最大Aggregate大小 | 256 TB原始容量^2^ 


| 每個集合體的磁碟數 | 1-6 ^3^ 


| 每個Aggregate的RAID群組數目上限 | 1. 
|===
附註：

. 資料集合體的最大數量不包括根Aggregate。
. 組成聚合的磁碟決定了聚合容量限制。此限制不包括用於資料分層的物件儲存。
. 集合體中的所有磁碟大小必須相同。




== 磁碟和分層限制

下表顯示單一磁碟的最大系統容量、以及磁碟和冷資料分層至物件儲存設備的最大系統容量。磁碟限制僅適用於包含使用者資料的磁碟。限制不包括開機磁碟、根磁碟或NVRAM。

[cols="60,40"]
|===
| 參數 | 限制 


| 最大資料磁碟數  a| 
* 124適用於單一節點系統
* 每個節點123個、適用於HA配對




| 最大磁碟大小 | 64 TB 


| 僅使用磁碟即可獲得最大系統容量 | 256 TB ^1^ 


| 利用磁碟和冷資料分層、將系統容量最大化至Google Cloud Storage儲存庫 | 視授權而定。請參閱上述的最大系統容量限制。 
|===
此限制是由Google Cloud Platform中的虛擬機器限制所定義。



== 儲存VM限制

有些組態可讓您建立更多的儲存VM（SVM）以Cloud Volumes ONTAP 供支援。

這些都是經過測試的極限。不支援配置更多儲存虛擬機器。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["瞭解如何建立額外的儲存VM"^]。

[cols="2*"]
|===
| 授權類型 | 儲存VM限制 


| * Freemium *  a| 
總共24個儲存VM ^1^



| *容量型PAYGO或BYOL*^2^  a| 
總共24個儲存VM ^1^



| *節點型BYOL*^3^  a| 
總共24個儲存VM ^1^



| *基於節點的PAYGO*  a| 
* 1個儲存VM、用於處理資料
* 1個儲存VM、用於災難恢復


|===
. 這24個儲存虛擬機器可提供資料、或是設定災難恢復（DR）。
. 對於容量型授權、額外的儲存虛擬機器不需要額外的授權成本、但每個儲存虛擬機器的最低容量費用為4 TiB。例如、如果您建立兩個儲存VM、每個VM都有2個TiB的已配置容量、則總共會收取8 TiB的費用。
. 對於基於節點的 BYOL，除了預設隨Cloud Volumes ONTAP附帶的第一個儲存虛擬機器之外，每個額外的_資料服務_儲存虛擬機器都需要附加授權。聯絡您的客戶團隊以取得儲存 VM 附加授權。
+
您設定用於災難恢復（DR）的儲存VM不需要附加授權（免費）、但它們確實會根據儲存VM的限制而計算。例如、如果您有12個資料服務儲存VM和12個儲存VM設定用於災難恢復、則您已經達到極限、無法建立任何其他儲存VM。





== 邏輯儲存限制

[cols="22,22,56"]
|===
| 邏輯儲存設備 | 參數 | 限制 


.2+| *檔案* | 最大大小 ^2^ | 128 TB 


| 每個Volume的最大值 | 磁碟區大小視情況而定、高達20億 


| * FlexClone Volumes * | 階層式複製深度：^12^ | 499年 


.3+| *《*》卷* FlexVol | 每個節點的最大值 | 500 


| 最小尺寸 | 20 MB 


| 最大大小 ^3^ | 300 TiB 


| * qtree * | 每FlexVol 個速度區塊的最大值 | 4、995 


| * Snapshot複本* | 每FlexVol 個速度區塊的最大值 | 1、023 
|===
. 階層式複製深度是FlexClone Volume的巢狀階層架構深度上限、可從單FlexVol 一的實體磁碟區建立。
. 從 ONTAP 9.12.1P2 開始、上限為 128 TB 。在 ONTAP 9.11.1 及更早版本中、上限為 16 TB 。
. 使用下列工具和最低版本、可建立最多 300 TiB 的 FlexVol Volume ：
+
** 從 Cloud Volumes ONTAP 9.12.1 P2 和 9.13.0 P2 開始、系統管理員和 ONTAP CLI
** BlueXP 從 Cloud Volumes ONTAP 9.13.1 開始






== iSCSI儲存限制

[cols="3*"]
|===
| iSCSI儲存設備 | 參數 | 限制 


.4+| * LUN* | 每個節點的最大值 | 1 、 024 


| LUN對應的最大數目 | 1 、 024 


| 最大尺寸 | 16 TB 


| 每個Volume的最大值 | 512 


| *群組* | 每個節點的最大值 | 256 


.2+| *啟動器* | 每個節點的最大值 | 512 


| 每個igroup的最大值 | 128/128 


| * iSCSI工作階段* | 每個節點的最大值 | 1 、 024 


.2+| *生命* | 每個連接埠的上限 | 1. 


| 每個連接埠集的上限 | 32 


| * PortSets* | 每個節點的最大值 | 256 
|===


== 不支援立即儲存恢復的部分Cloud Volumes ONTAP

節點重新開機後、合作夥伴必須先同步資料、才能退回儲存設備。重新同步資料所需的時間取決於節點當機時用戶端寫入的資料量、以及恢復期間的資料寫入速度。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["瞭解 Cloud Volumes ONTAP HA 配對在 Google Cloud 中的儲存功能如何運作"^]。
