---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: 包含全新增強功能的支援功能Cloud Volumes ONTAP 。 
---
= 更新功能Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
包含全新增強功能的支援功能Cloud Volumes ONTAP 。

最新版的BlueXP（前身為Cloud Manager）也引進其他功能與增強功能。請參閱 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^] 以取得詳細資料。



== 9.13.0 GA（2023年3月5日）

AWS、Azure和Google Cloud現已推出通用（GA）版本Cloud Volumes ONTAP 的《支援》（General Availability、GA）。此版本包含下列新功能與增強功能。



=== Google Cloud的Flash Cache和高速寫入速度

支援Flash Cache、高速寫入速度、以及高傳輸單位（MTU）8、896位元組、現在Cloud Volumes ONTAP 可用於發行版本為《The》（英文）的特定執行個體。

深入瞭解 link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google Cloud授權支援的組態"^]。



=== 在Google Cloud中驗證影像

現在提供增強的安全功能、可驗證Cloud Volumes ONTAP 透過Google Cloud匯出的各種圖片檔案的簽名。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-gcp-image-verification.html["深入瞭解Google Cloud Image驗證"^]。



=== Google Cloud提供新的執行個體支援

Freemium、PAYGO Premium、節點型BYOL及容量型授權現在支援兩種新的執行個體類型、可在Cloud Volumes ONTAP Google Cloud中進行單一節點與高可用度部署。

* n2-Standard-48
* n2-Standard-64


link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["深入瞭解Google Cloud支援的組態"^]。



== 升級附註

請閱讀這些附註、深入瞭解升級至此版本的相關資訊。



=== 如何升級

必須從BlueXP完成升級。Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。

link:http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在BlueXP通知您時進行升級"^]。



=== 支援的升級途徑

您可以從Cloud Volumes ONTAP 9.12.1版升級至版本的支援。BlueXP會提示您將合格Cloud Volumes ONTAP 的更新版升級至此版本。



=== 所需版本的Connector

BlueXP Connector必須執行3.9.26版或更新版本、才能部署新Cloud Volumes ONTAP 的版本的更新版本、並將現有系統升級至9.13.0版。


TIP: 連接器的自動升級預設為啟用、因此您應該執行最新版本。



=== 停機

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。




=== 不再支援c4、m4和r4執行個體

在AWS中Cloud Volumes ONTAP 、不再支援C4、M4和R4 EC2執行個體類型。如果現有的系統執行於c4、m4或r4執行個體類型、則必須變更為c5、m5或R5執行個體系列中的執行個體類型。您必須變更執行個體類型、才能升級至此版本。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["瞭解如何變更EC2執行個體類型Cloud Volumes ONTAP 以供使用"^]。

請參閱 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp支援"^] 以深入瞭解這些執行個體類型的終止可用度和支援。
